version: '3.1'

services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: telegram_bot
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
        context: .
        dockerfile: Dockerfile
    command: python3 main.py
    environment:
        DB_HOST: db
        DB_NAME: telegram_bot
        DB_USER: postgres
        DB_PASS: postgres
        DB_PORT: 5432
        ADMIN_TOKEN: "asdfghjklhgfdsasdfghjklat4asfytfaasdfghjkl_AAFtPZOZM5yplfXkIMw4U_TalFr3912I14s"
        TOKEN: ${TOKEN}
    depends_on:
      - db
  #  volumes:
  #    - .:/app

volumes:
    postgres_data:
